ROMIO: add --enable-fortran configure option
pmodels/mpich pull request #4691
Opened 2020-07-04 09:11 UTC by wkliao

## Pull Request Description
Note MPICH configure option --enable-fortran/--disable-fortran is
passed down to ROMIO.

## Expected Impact

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

2021-06-14 00:11 UTC, hzhou commented
@wkliao This one looks fine to merge. Could you rebase this PR?

2022-04-18 01:17 UTC, hzhou requested changes
Sorry that I forgot about this one. The options in main mpich configure has changed a little. The current fortran options are -- https://github.com/pmodels/mpich/blob/3494619ecdd413427f7638e274c9f70a1960e80a/configure.ac#L441-L452

2022-04-18 18:38 UTC, wkliao commented
> Sorry that I forgot about this one. The options in main mpich configure has changed a little. The current fortran options are --
> 
> https://github.com/pmodels/mpich/blob/3494619ecdd413427f7638e274c9f70a1960e80a/configure.ac#L441-L452

These are already in my changes.

2022-04-18 18:56 UTC, hzhou commented on src/mpi/romio/configure.ac
> +    [enable_fc=${enableval}], [enable_fc=yes])
MPICH now uses `--disable-f90` rather than than `--disable-fc`.

2022-04-19 22:09 UTC, hzhou commented on src/mpi/romio/configure.ac
> + if test "$FORTRAN_MPI_OFFSET" = "integer*8" && test "A$MPI_OFFSET_KIND2" = "A!" && test $NOF77 = 0 && (test $NOF90 = 0 || test $NOF08 = 0) ; then
I am not quite clear about the logic here. Can someone explain in plain English? @wkliao @roblatham00

2022-04-20 03:07 UTC, wkliao commented
That is a very old code. I believe it is to figure out MPI_OFFSET_KIND and save in include/mpiof.h, as KIND is introduced in F90.
```
      INTEGER MPI_OFFSET_KIND
      PARAMETER (MPI_OFFSET_KIND=           8)
```
or
```
      INTEGER MPI_OFFSET_KIND
      PARAMETER (MPI_OFFSET_KIND=           4)
```

2022-04-20 19:47 UTC, hzhou commented
> That is a very old code. I believe it is to figure out MPI_OFFSET_KIND and save in include/mpiof.h, as KIND is introduced in F90.
> 
> ```
>       INTEGER MPI_OFFSET_KIND
>       PARAMETER (MPI_OFFSET_KIND=           8)
> ```
> 
> or
> 
> ```
>       INTEGER MPI_OFFSET_KIND
>       PARAMETER (MPI_OFFSET_KIND=           4)
> ```

If it is trying to test whether it is F90 compiler, I think we can simply remove the check. MPICH is now requiring F90 compilers. And today it is difficult to find a legacy F77 compiler in the wild anyway.

2022-04-20 21:00 UTC, wkliao commented
It is not to test whether the Fortran compiler is a F90.
That codes update include/mpiof.h.
However, I think mpiof.h can be removed completely.
as mpif.h has already covered all the necessities.
There can be a separate new PR for that task.
FYI. A related PR is #4693

2022-04-20 21:30 UTC, hzhou commented
> It is not to test whether the Fortran compiler is a F90. That codes update include/mpiof.h. However, I think mpiof.h can be removed completely. as mpif.h has already covered all the necessities. There can be a separate new PR for that task. FYI. A related PR is #4693

#4693 is merged!

2024-04-20 20:54 UTC, wkliao commented
Close as this affects only #6956

2024-04-20 20:54 UTC, closed without merging