Fixing typo
pmodels/mpich pull request #4995
Opened 2021-01-12 20:28 UTC by markalle

* first commit:
from wkliao:  lock contiguous indpendent write when data sieving write is not disabled

* second commit:
fixing a likely cut-and-paste typo

2021-01-12 21:04 UTC, markalle commented
I had to squash my typo fix into wkliao's sieving code because apparently the whitespace checker won't allow an indentation issue in one commit with an indentation fix in the next commit.  I guess it wants every individual commit to pass the indentation tests.

2021-01-12 21:13 UTC, hzhou commented
> I had to squash my typo fix into wkliao's sieving code because apparently the whitespace checker won't allow an indentation issue in one commit with an indentation fix in the next commit. I guess it wants every individual commit to pass the indentation tests.

Yep. It is a pain in xxx, but it's what we decided for the greater good

2021-01-21 17:44 UTC, markalle commented
Most of the discussion for this bug is over here:
https://github.com/pmodels/mpich/pull/4956
where I had made a different fix, then @wkliao made a more targeted fix shown here.

2021-01-21 17:46 UTC, markalle commented
test:mpich/warnings

2021-01-21 17:52 UTC, hzhou commented
@markalle  I need check the Jenkins cofig, but it appears that we may have to add your name to a list in order for the CI to run. For now, let me do it for you --

test:mpich/warnings
test:mpich/ch3/most
test:mpich/ch4/most

2021-02-03 19:41 UTC, markalle commented
I don't think I have permission to add reviewers.  @wkliao I know you looked at this before and said it looked fine, but can you approve it so it can be merged in?

2021-02-03 19:45 UTC, hzhou commented
The title is wrong, there are more stuff going on. The description says there are two commits, but I only see one

2021-02-04 21:14 UTC, roblatham00 approved these changes
Makes me a little uneasy to add locks around contiguous writes...  however this is inside the strided i/o path, and it seems like we short-circuited too much when we detected this optimization opportunity.    Ship it!

2021-02-04 21:17 UTC, hzhou requested changes
> The title is wrong, there are more stuff going on. The description says there are two commits, but I only see one

@markalle If you rebase to main and address above comments, we'll merge it.

2021-02-09 21:21 UTC, markalle commented
I updated the commit message and the message at the top of the PR

2021-03-01 02:39 UTC, markalle commented
@hzhou I fixed the commit title and body a little while back so I think this should be ready to merge.  I hadn't changed the PR title to match though so I did that just now too.

2021-03-01 02:43 UTC, hzhou commented
test:mpich/warnings
test:mpich/ch4/most
test:mpich/ch3/most

2021-03-02 14:33 UTC, gpaulsen commented
@hzhou, look good?

2021-03-02 15:06 UTC, hzhou commented
Rebased to main, will merge shortly

test:mpich/warnings

2021-03-02 15:25 UTC, hzhou approved these changes

2021-03-02 15:25 UTC, merged