Hydra: Add parsing of MPIEXEC_PREFIX_DEFAULT
pmodels/mpich pull request #5135
Opened 2021-03-09 23:02 UTC by travisk1154

## Pull Request Description
There was no handling of the environment variable MPIEXEC_PREFIX_DEFAULT in the hydra code base. The variable adds the rank as a prefix to stdout in the form [%r] by settings its value to anything greated than zero. A new function, HYD_check_envs, was created to handle this and can be used for the handling of other environment variables in the future. The already existing function, prepend_rank_fn, is used to add the pattern to stdout. This function checks for duplicate settings so using both MPIEXEC_PREFIX_DEFAULT and -prepend-rank will correctly result in an error. These new settings were tested manually and can
confirm that it works as intended.

Fixes #4388 

## TODO
* [x] Confirm user reported issue
* [x] Implement Fix
* [x] Test Fix

## Expected Impact
Users will now be able to user environment variable MPIEXEC_PREFIX_DEFAULT

## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

2021-03-09 23:21 UTC, hzhou commented on src/pm/hydra/ui/mpich/utils.c
> +
The internal function should be declared as `static` and you don't need a namespace for static functions.

2021-03-10 23:29 UTC, hzhou requested changes

2021-03-10 23:29 UTC, hzhou commented on src/pm/hydra/ui/mpich/utils.c
> +    char *arg = "MPIEXEC_PREFIX_DEFAULT";
Remove the extra variable.

2021-03-10 23:29 UTC, hzhou commented on src/pm/hydra/ui/mpich/utils.c
> +            status = HYDU_set_str(arg, &HYD_ui_info.prepend_pattern, "[%r] ");
Do `HYDU_ERR_POP(status, ...)`, and add `fn_fail`, `fn_exit` labels. This way in the future when we add addition environment variable, one wouldn't easily overwritten the status return.

2021-03-10 23:29 UTC, hzhou commented on src/pm/hydra/ui/mpich/utils.c
> +    HYDU_ERR_POP(status, "error setting environment variable\n");
`status = check_envs();`

2021-03-10 23:31 UTC, hzhou commented on src/pm/hydra/ui/mpich/utils.c
> +            status = HYDU_set_str(arg, &HYD_ui_info.prepend_pattern, "[%r] ");
When later during command-line parsing, and if additional `-l` is given and we set the string twice, does it result in memory leak? Please double check.

2021-03-12 03:27 UTC, hzhou commented
@travisk1154 Looks good. Could you swap the order of the commits? That way we keep each commits to be able to compile clean.

Also, did you manually test and confirm the user issue is fixed?

2021-03-12 03:28 UTC, hzhou commented
test: mpich/ch4/ofi

2021-03-12 15:26 UTC, travisk1154 commented
Yea I have manually tested things. Setting `MPIEXEC_PREFIX_DEFAULT` to equal 1 or higher adds the rank successfully. Anything equal to zero or lower does not do anything. Having `MPIEXEC_PREFIX_DEFAULT=1` and `-prepend-rank` sends and error and stops the program as expected. Having `MPIEXEC_PREFIX_DEFAULT=0` and `-prepend-rank` adds the rank as expected.

2021-03-12 15:54 UTC, hzhou commented
> Having `MPIEXEC_PREFIX_DEFAULT=1` and `-prepend-rank` sends and error and stops the program as expected.

This is not ideal

2021-03-12 15:56 UTC, hzhou approved these changes
Other than the non-ideal behavior when we have conflicting options via environment and command options -- currently it results in error, ideally we'd like the command option take priority -- this PR addresses the issue and IMO it's ok to merge.

2021-03-18 03:17 UTC, hzhou requested changes

2021-03-18 03:17 UTC, hzhou commented on src/pm/hydra/ui/mpich/utils.c
> +    }
The point of processing environment in `check_envs` is so we don't check environment again in another place.

2022-02-21 15:25 UTC, hzhou commented
We decided to remove these environment variables. See #5848.

2022-02-21 15:25 UTC, closed without merging