hydra: add %t to -prepend-pattern
pmodels/mpich pull request #5170
Opened 2021-03-23 17:02 UTC by hzhou

## Pull Request Description

Adds simple timing info to the output messages. This provides a quick
and rough timing that can be handy for some debugging purposes.

## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

2021-03-23 17:03 UTC, hzhou commented
test:mpich/custom
netmod: ch4:ofi

2021-04-16 15:14 UTC, raffenet requested changes
Can you update the help text, also? https://github.com/pmodels/mpich/blob/67c5d0713e393cbddb7b418a0f6b71deb487cc97/src/pm/hydra/ui/mpich/utils.c#L468-L475

2021-04-16 20:57 UTC, hzhou commented
@raffenet Fixed and updated.

2021-04-18 18:57 UTC, raffenet approved these changes

2021-04-20 04:26 UTC, merged