object: fix compilation error from ref release
pmodels/mpich pull request #5217
Opened 2021-04-14 22:29 UTC by sagarth

## Pull Request Description

`new_ref_` was being accessed outside of its scope after the else block.

## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

2021-04-14 22:32 UTC, hzhou requested changes

2021-04-14 22:32 UTC, hzhou commented on src/include/mpir_objects.h
>              *(inuse_ptr) = 0;                                                  \
set `new_ref` to `0` here.

2021-04-14 22:37 UTC, sagarth commented on src/include/mpir_objects.h
>              *(inuse_ptr) = 0;                                                  \
Oops missed that part. Fixed it.

2021-04-14 22:45 UTC, hzhou approved these changes

2021-04-14 22:45 UTC, hzhou commented
test:mpich/ch4/most
test:mpich/ch3/most

2021-04-15 00:41 UTC, hzhou commented
test:mpich/ch4/ofi

2021-04-15 13:33 UTC, merged