doc: update documents to reflect changes in test/mpi
pmodels/mpich pull request #5711
Opened 2021-12-02 22:58 UTC by hzhou

## Pull Request Description
The test suite can be configured and run independently. Update misc documents to reflect it.

[skip warnings]

## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

2021-12-08 17:32 UTC, raffenet requested changes
A few minor suggested tweaks.

2021-12-08 17:32 UTC, raffenet commented on CHANGES
> +# Testsuite (test/mpi) are configured separately from mpich configure.
```suggestion
# Testsuite (test/mpi) is configured separately from mpich configure.
```

2021-12-08 17:32 UTC, raffenet commented on doc/installguide/install.tex.vin
> +build MPICH. Go to \texttt{test/mpi}` directory and
```suggestion
The MPICH test suite can be used to test any MPI implementations, not just MPICH.
To test a pre-installed MPI implementation, there is no need to configure and
build MPICH. Go to \texttt{test/mpi}` directory and
```

2021-12-08 17:32 UTC, raffenet commented on doc/installguide/install.tex.vin
> +    configure --with-mpi=/path/to/mpi
```suggestion
    ./configure --with-mpi=/path/to/mpi
```

2021-12-08 20:41 UTC, hzhou commented on doc/installguide/install.tex.vin
> +    configure --with-mpi=/path/to/mpi
Thanks. All fixed.

2021-12-22 15:37 UTC, raffenet approved these changes

2021-12-22 15:47 UTC, merged