testsuite: workaround lack of deleted APIs
pmodels/mpich pull request #6279
Opened 2022-11-16 11:50 UTC by jeffhammond

conditionalize use of datatype functions that were deleted in MPI-3:
- MPI_Type_hvector
- MPI_Type_hindexed

## Pull Request Description

## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

2022-11-16 17:12 UTC, hzhou requested changes

2022-11-16 17:12 UTC, hzhou commented on test/mpi/dtpools/src/dtpools_custom.c
> +#endif
I would suggest just use the new function, i.e. `MPI_Type_create_hvector`. `MPI-1` implementations can always use older testsuite releases.

2022-11-16 17:39 UTC, jeffhammond commented
it is one clean simple commit now

2022-11-16 17:47 UTC, hzhou approved these changes
Approved. Please check the PR checklist and clear the tests.

2022-11-21 20:11 UTC, raffenet commented
test:mpich/ch4/ofi

2022-11-21 20:16 UTC, raffenet commented
Fixed the whitespace complaint. This should be ready to go.

2022-11-21 20:22 UTC, merged