fix compiler warning for format
pmodels/mpich pull request #6283
Opened 2022-11-16 12:27 UTC by jeffhammond

printing MPI_Count should use a wider type. this isn't perfect, since MPI_Count can be anything, but long long is better than long.

parrived_wait.c:66:68: warning: format specifies type 'long' but the argument has type 'MPI_Count' (aka 'long long') [-Wformat]
                        rank, tid, exp_val, buf[index], index, rp, rcount, i, iter);

## Pull Request Description

## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

2022-11-16 17:06 UTC, hzhou requested changes

2022-11-16 17:06 UTC, hzhou commented on test/mpi/part/parrived.c
>                          exp_val, buf[index], index, rp, rcount, i, iter);
The compiler will warn if `MPI_Count` is not a `long long`. One work around is to also add a cast to the value -
`,  (long long) rcount, `

2022-11-21 20:54 UTC, raffenet commented
test:mpich/ch4/ofi

2022-11-21 21:44 UTC, hzhou approved these changes
LGTM

2022-11-21 21:59 UTC, merged