submodules: update Yaksa
pmodels/mpich pull request #6700
Opened 2023-09-28 20:39 UTC by yfguo

## Pull Request Description

Bring the Yaksa submodule up to date for CUDA capability detection and other changes.
## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

2023-10-02 14:50 UTC, raffenet commented
Can you reference the yaksa PRs in the commit message? That way its easy to trace which code this pulls in.

2023-10-06 15:13 UTC, raffenet commented
As discussed on the 10/5 development call, we should add a line in CHANGES (and perhaps README) noting the change to the default yaksa configuration to use automatic CUDA device detection rather than building everything supported by the CUDA installation.

2023-10-17 21:18 UTC, raffenet requested changes
see previous comments on the PR. this is good to go just want to leave ourselves a trail to remind us what changed and when.

2023-10-18 16:14 UTC, yfguo commented
> see previous comments on the PR. this is good to go just want to leave ourselves a trail to remind us what changed and when.

Added description in `CHANGES`.

2023-10-19 21:20 UTC, raffenet commented on CHANGES
> +# Yaksa updated to build auto detect the GPU architecture and only build for
```suggestion
# Yaksa updated to auto detect the GPU architecture and only build for
```

2023-10-20 20:16 UTC, raffenet approved these changes

2023-10-20 20:17 UTC, raffenet commented
test:mpich/ch4/most
test:mpich/ch4/gpu

2023-10-23 17:29 UTC, merged