comm: create communicator from group
pmodels/mpich pull request #7237
Opened 2024-12-11 21:43 UTC by hzhou

## Pull Request Description
First there is only `MPI_COMM_WORLD`. Later we added dynamic processes, MPI groups, and lately, MPI sessions. Because these later concepts are not part of original vision, they implemented by hacking rather than by design. For example, instead of we locally create group then create communicator from group, we do it in reverse. We assume the communicator is always there -- an `MPI_COMM_WORLD` which can later split and recombine -- and we derive groups from existing communicators. In the original design, all the process addressing system is based on communicators. It is a mess! The latest addition of MPI session throw a wrench to this mess because now we have a situation that communicators are not always there.

The current situation:
* MPIR `comm` uses mapper -- an address systems based parent communicators
    * `MPIR_Comm_map_t`
* Device layer constructs its own address system from the mapper
    * ch3 constructs  `MPIDI_VCRT` table for each communicator based on the mapper
        * Optimizations to reuse `vcrt` in the dup case
    * ch4 constructs `MPIDI_rank_map_t` which refers to a global `avt_mgr` (av table manager)
* The device layer constructs a process id `lpid`, accessed using `MPID_Comm_get_lpid`
* When needed, MPI groups are constructed from a communicator using `lpid`s

This convoluted mess is because we designed `lpid` to be device-layer opaque and mysterious. Within the current upstream code base, we have 4 address systems -
* MPIR Comm `mapper`
* ch3 `VCRT`
* ch4 av table manager
* MPI Group
And we are about to add "MPI Session PSET", yet another address system

I propose to unite all into a single system and make MPI Group first-class citizen.
We can use a universal address system using (`world_idx`, `world_rank`) combination.

In the hind sight, we should design it the session way --
* process manager create the world
* process `init` discover the world
* process create MPI groups
* process create communicators from groups
* device layer make communicators function by establish the communication layer

The PR tries to do just that.

[skip warnings]

## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

2024-12-12 17:35 UTC, hzhou commented
test:mpich/ch4/ofi

2024-12-12 22:00 UTC, hzhou commented
test:mpich/ch4/ofi

2024-12-13 13:55 UTC, hzhou commented
test:mpich/ch3/most
test:mpich/ch4/most

2024-12-26 21:00 UTC, hzhou commented
test:mpich/ch4/ofi

2025-01-15 20:31 UTC, yfguo requested changes

2025-02-11 19:53 UTC, hzhou commented on src/mpid/ch4/src/ch4_comm.c
> +        MPIR_Assert(sizeof(MPIR_Lpid) == 4);
Right. Updated.

2025-02-11 20:01 UTC, hzhou commented on src/mpi/comm/builtin_comms.c
> +    MPIR_Group_add_ref(MPIR_GROUP_WORLD_PTR);
Good suggestion. Added.

2025-02-11 20:04 UTC, hzhou commented on src/mpi/comm/comm_impl.c
> +
Fixed.

2025-02-11 20:05 UTC, hzhou commented on src/mpid/ch4/src/init_comm.c
> +         * runtime features for stability during init */
White space checker, tab to space.

2025-02-11 20:07 UTC, hzhou commented
test:mpich/ch3/most
test:mpich/ch4/most

2025-02-11 20:57 UTC, hzhou commented
test:mpich/ch3/most
test:mpich/ch4/most

2025-02-11 21:01 UTC, hzhou commented
test:mpich/ch3/most
test:mpich/ch4/most

2025-02-12 02:22 UTC, hzhou commented
test:mpich/ch3/most
test:mpich/ch4/most

2025-02-12 02:36 UTC, hzhou commented
test:mpich/ch3/most
test:mpich/ch4/most

2025-02-14 18:29 UTC, raffenet approved these changes

2025-02-14 18:29 UTC, raffenet commented on src/mpid/ch4/src/ch4_impl.h
> +        if (gpid == (uint64_t) MPIR_Group_rank_to_lpid(grp, z)) {
We could probably change the type of `gpid` in this commit [a5b687e8b2445ac25d5711760c2c8e4906fe6b18]. The next one addresses it, so I guess it's OK.

2025-02-24 23:30 UTC, merged