ch3: refactor to remove the usage of comm mapper
pmodels/mpich pull request #7242
Opened 2024-12-19 02:38 UTC by hzhou

## Pull Request Description
Based on #7235, #7237

Now the `local_group` and `remote_group` in `MPIR_Comm` can fully replace the functions of mapper, refactor ch3 to use group instead of mapper in `MPIDI_CH3I_Comm_commit_pre_hook`.

[skip warnings]

## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

2024-12-19 03:32 UTC, hzhou commented
test:mpich/ch3/most

2024-12-20 04:37 UTC, hzhou commented
test:mpich/ch3/most

2024-12-20 15:59 UTC, hzhou commented
test:mpich/custom
netmod: ch3/tcp
config: debug

2024-12-20 16:08 UTC, hzhou commented
test:mpich/custom
netmod: ch3:tcp
config: debug

2024-12-20 23:02 UTC, hzhou commented
test:mpich/custom
netmod: ch3:tcp
config: debug

2024-12-21 02:34 UTC, hzhou commented
test:mpich/custom
netmod: ch3:tcp
config: debug

2024-12-21 03:38 UTC, hzhou commented
test:mpich/custom
netmod: ch3:tcp
config: debug

2024-12-21 14:08 UTC, hzhou commented
test:mpich/ch3/most
test:mpich/ch4/most

test:mpich/custom
netmod: ch3:tcp
config: debug

2024-12-21 15:04 UTC, hzhou commented
test:mpich/ch3/most
test:mpich/ch4/most

2024-12-22 03:51 UTC, hzhou commented
test:mpich/ch3/most
test:mpich/ch4/most

2024-12-22 05:35 UTC, hzhou commented
test:mpich/ch3/most
test:mpich/ch4/most

2024-12-22 17:02 UTC, hzhou commented
test:mpich/ch3/most
test:mpich/ch4/most

2024-12-22 17:29 UTC, hzhou commented
test:mpich/ch3/most
test:mpich/ch4/most

2025-01-15 20:50 UTC, yfguo requested changes

2025-01-15 20:50 UTC, yfguo commented on src/include/mpir_group.h
> +#define MPIR_LPID_WORLD_INDEX(lpid) ((lpid) >> 32)
Should the bit for DYNAMIC be cleared before converting to world index?

2025-01-15 20:50 UTC, yfguo commented on src/mpi/group/grouputil.c
> +    memcpy(&(*new_group_ptr)->pmap, &old_group->pmap, sizeof(struct MPIR_Pmap));
Related to comment on map reusing  in PR #7235, should we add refcount to `MPIR_Pmap` so that it can be easily shared in most of the scenario. This would reduce memory usage due to these linear data structures.

2025-01-15 20:50 UTC, yfguo commented on src/mpi/group/grouputil.c
> +
Remove blank line. Only updating code format if this is update to code logic. This would reduce potential merge conflict.

2025-02-25 16:31 UTC, hzhou commented on src/mpi/group/grouputil.c
> +    memcpy(&(*new_group_ptr)->pmap, &old_group->pmap, sizeof(struct MPIR_Pmap));
`MPIR_Pmap` is never shared and belong to an `MPIR_Group`. `MPIR_Group`, on the other hand, can be shared by comms or psets, and they are reference-counted.

2025-02-25 16:32 UTC, hzhou commented on src/mpi/group/grouputil.c
> +
It's gone.

2025-02-25 16:42 UTC, hzhou commented
test:mpich/ch3/most
test:mpich/ch4/most

2025-03-05 18:19 UTC, raffenet reviewed
just a minor comment for clarification

2025-03-05 18:19 UTC, raffenet commented on src/mpi/group/grouputil.c
> +#endif
Are there functional changes in this [patch](d0a5ad41bb1e4dc99b1d245eff0a8c1c9b20ac04)? I guess there is the addition of the device-layer hook, but otherwise it looks to just be style changes.

2025-03-05 19:17 UTC, hzhou commented on src/mpi/group/grouputil.c
> +#endif
Hmm, it's possible `MPIR_Group_dup` has already been added in the previous PRs, resulting here only style changes. I'll double check and clean it up.

2025-03-06 14:52 UTC, hzhou commented on src/mpi/group/grouputil.c
> +#endif
I dropped this commit. Let's see if the tests catch anything.

2025-03-06 14:53 UTC, hzhou commented
test:mpich/ch3/most
test:mpich/ch4/most

2025-03-06 21:04 UTC, raffenet approved these changes
LGTM

2025-03-06 21:06 UTC, merged